# Project
projectGroup=com.goormthon
projectVersion=0.0.1
kotlinVersion=1.9.20

# Lint
ktLintPluginVersion=12.1.2
ktLintVersion=1.0.1

# Spring dependency versions
springBootVersion=3.4.4
springDependencyManagementVersion=1.1.7

# Library versions
jjwtVersion=0.12.6
postgresqlVersion=42.7.2
springDocOpenApiVersion=2.8.13
springMockkVersion=4.0.2
mockitoVersion=5.14.0
mockitoKotlinVersion=5.4.0
instancioJUnitVersion=5.0.2
kotlinLoggingJvmVersion=7.0.3
redissonVersion=3.30.0

kotlin.daemon.jvmargs=-Xmx1g -XX:MaxMetaspaceSize=512m