apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: redis
data:
  redis.conf: |
    # Redis configuration file

    # Persistence
    appendonly yes
    appendfsync everysec

    # Memory
    maxmemory 450mb
    maxmemory-policy allkeys-lru

    # Logging
    loglevel notice

    # Network
    bind 0.0.0.0
    protected-mode no
    port 6379

    # Performance
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
