apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goormthon-6

resources:
  - configmap.yaml
  - service.yaml
  - statefulset.yaml

images:
  - name: redis:7.2-alpine
    newName: redis
    newTag: "7.2-alpine"
